
services:

  esph-sysmon:

    container_name: esph-sysmon

    build:
      context: .

    volumes:
      - ./sysmon.yaml:/config/run.yaml:ro
      - ./include.h:/config/include.h:ro
      - /etc/localtime:/etc/localtime:ro

    restart: unless-stopped

    healthcheck:
      disable: true

#    network_mode: host

networks:

  default:
    external: true
    name: rpidock
