esphome:

  name: test-ch341

  on_boot:
    - priority: 100
      then:
        - logger.log: "Host platform running!"
    - priority: -100
      then:
        - lambda: setlinebuf( stdout );

external_components:

  - source:
      type: git
      url: https://github.com/MeisterSchlaueLampe/esphost.git
      ref: main
    components: [ ch341_i2c , i2c ]

host:

api:

logger:

  level: VERBOSE

i2c:

  id: dummy_i2c
  linux_device: /dummy/dev

ch341_i2c:

  id: i2c_bus_ch341
  frequency: 100kHz  # or 20kHz, 400kHz, 750kHz
  scan: true

sensor:

  - platform: bme280_i2c
    address: 0x76
    update_interval: 60s
    i2c_id: i2c_bus_ch341
    temperature:
      name: "Temperature"
    humidity:
      name: "Humidity"
    pressure:
      name: "Pressure"
